#!/usr/bin/env ruby

# Would be nice to make this a bash script instead so it can be run on a box
# that does not need Ruby installed.

# Run this after cloning to symlink things correctly
# Or, run again to ensure the symlinks are up to date
# (Hence, the script should be idempotent)

if ARGV.count != 2
  puts 'This script sets up the dotfiles (conf) folder on this system.'
  puts 'It should be run from your home directory.'
  abort 'Usage: setup <platform_name> <host_name>'
end

puts 'Configuring dotfiles repo...'

def symlink_if_not_present_or_existing_symlink src, dest = File.basename(src)
  if !File.exist?(dest) || File.symlink?(dest)
    `ln -sf #{src} .`
  else
    # AP 20140214 - this is a bit paranoid
    #abort <<-EOS
    #  Wanted to create symbolic link #{src} -> #{dest}, but a
    #  non-symlinked file was already there, which is unexpected. Aborting!
    #EOS
  end
end

[
 "conf/common/etc/.ackrc",
 "conf/common/etc/.actrc",
 "conf/common/etc/.aprc",
 "conf/common/etc/.bash_profile",
 "conf/common/etc/.bashrc",
 "conf/common/etc/.ctags",
 "conf/common/etc/.cvsignore",
 "conf/common/etc/.emacs",
 "conf/common/etc/.fzf.bash",
 "conf/common/etc/.fzf.zsh",
 "conf/common/etc/.gemrc",
 "conf/common/etc/.gitconfig",
 "conf/common/etc/.gitignore",
 "conf/common/etc/.gvimrc",
 "conf/common/etc/.hushlogin",
 "conf/common/etc/.irbrc",
 "conf/common/etc/.rvmrc",
 "conf/common/etc/.tmux.conf",
 "conf/common/etc/.tryrc.json",
 "conf/common/etc/.vimrc",
 "conf/common/etc/.yarnrc",
 "conf/common/etc/.zshrc.end",

 "conf/common/.vim",
].each do |filename|
  symlink_if_not_present_or_existing_symlink filename
end

# set up vim temporary directories
# based on my .vimrc custom configuration
['backup', 'swap', 'undo'].each do |tmpfile|
  `mkdir -p ~/.vim/tmp/#{tmpfile}`
end

# set up emacs temporary directory
# based on my .emacs custom configuration
`mkdir -p ~/conf/tmp/emacs`

# ~/.config symlinks
# Auto-discovers everything under conf/common/etc/.config/ and symlinks it into
# ~/.config/, creating parent directories as needed. To add a new config, just
# drop the file into conf/common/etc/.config/<app>/<file>.
config_src = File.expand_path('~/conf/common/etc/.config')
Dir.glob("#{config_src}/**/*").select { |f| File.file?(f) }.each do |src_path|
  relative = src_path.sub("#{config_src}/", '')
  dest = File.expand_path("~/.config/#{relative}")
  dir = File.dirname(dest)
  `mkdir -p #{dir}`
  if !File.exist?(dest) || File.symlink?(dest)
    `ln -sf #{src_path} #{dest}`
    puts "  Linked ~/.config/#{relative}"
  else
    puts "  Skipped ~/.config/#{relative} (non-symlink file exists)"
  end
end

platform = ARGV[0]
host = ARGV[1]

`mkdir -p conf/platforms/#{platform}/etc`
`touch conf/platforms/#{platform}/etc/.zshrc`
`mkdir -p conf/hosts/#{host}/etc`
`touch conf/hosts/#{host}/etc/.zshrc`

File.open('.zshrc', 'w') do |f|
  f.puts <<-EOS
CONF=$HOME/conf
conf=$HOME/conf
PLATFORM='#{platform}'

path_to_zshrc=etc/.zshrc
source $CONF/init/$path_to_zshrc

PATH=$PATH:$HOME/.rvm/bin # Add RVM to PATH for scripting
  EOS
end

# run rake make inside ~/.vim/bundle/command-t
# otherwise we get:
# command-t.vim could not load the C extension
# Please see INSTALLATION and TROUBLE-SHOOTING in the help
# For more information type:    :help command-t
puts 'Configuring Command-T (Vim plugin)...'
`./conf/setup_command_t 2>&1 > /dev/null`

puts 'Setting up submodules...'

Dir.chdir('conf') do
  IO.popen('git submodule update --init --recursive') do |f|
    puts f.gets
  end
end

puts 'Dotfiles successfully configured!'
