#!/bin/sh

git submodule init

# Update each submodule
git submodule foreach '
    # Fetch the latest info from the remote
    git fetch

    # Try to determine the primary branch (main, master, release)
    # copilot-vim at least uses `release` as the primary branch name
    for branch in main master release; do
        if git show-ref --verify --quiet "refs/remotes/origin/$branch"; then
            echo "Updating $name to latest $branch"
            git checkout $branch
            git pull origin $branch
            break
        fi
    done
'
